#!/bin/bash

# This script will take care of the dependencies.
# These dependencies range from cloning SUMO, ns3-gym requirements
# as well as some third-party tools like PyTest and TensorFlow.
#
# The full list of requirements is listed in the README file
# this is because some dependencies are additional or OS dependent.
#
#
# To run this script just enter the following command in the terminal
# >> ./install_dep

echo "Installing pip3"
sudo apt-get update
sudo apt-get -y install python3-pip
pip3 --version
echo "** Done **"

echo "Installing pip"
sudo apt-get update
sudo apt-get -y install python-pip
pip --version
echo "** Done **"

echo "Installing PyTest"
pip3 install pytest
echo "** Done **"

echo "Installing BeautifulTable"
pip3 install beautifultable
echo "** Done **"

echo "Installing TensorFlow"
pip3 install tensorflow
echo "** Done **"

echo "Installing stablebaselines dependencies"
sudo apt-get update && sudo apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev
echo "** Done **"

echo "Installing StableBaselines"
echo "Which type of StableBaselines would you like?"
echo "[ 1 ] Regular"
echo "[ 2 ] With OpenMPI support"
echo "* Note: OpenMPI has been known to cause issues with Tensorflow in the past."

read sb_option
if [ $sb_option == 1  ]
then
        pip3 install stable-baselines
fi
if [ $sb_option == 2 ]
then
        pip3 install stable-baselines[mpi]
fi
echo "** Done **"

echo "Installing ns3-gym dependencies"
apt-get install gcc g++ python
sudo add-apt-repository ppa:maarten-fonville/protobuf
sudo apt-get update

apt-get install libzmq5 libzmq5-dev
apt-get install libprotobuf-dev
apt-get install protobuf-compiler

echo "Configuring and building ns3-gym"

# If you don't want examples then omit the option
./waf configure --enable-examples
./waf build

echo "** Done **"
echo "Installing gym add on"

pip3 install install ./src/opengym/model/ns3gym

echo "Installing SUMO and dependencies"
sudo apt-get update
sudo apt-get install -y cmake swig libgtest-dev python-pygame python-scipy
sudo apt-get install -y autoconf libtool pkg-config libgdal-dev libxerces-c-dev
sudo apt-get install -y libproj-dev libfox-1.6-dev libxml2-dev libxslt1-dev
sudo apt-get install -y build-essential curl unzip flex bison python python-dev
sudo apt-get install -y python3-dev
sudo pip3 install cmake cython
echo "** Done **"

echo "Installing SUMO binaries"
mkdir -p $HOME/sumo_binaries/bin/
pushd $HOME/sumo_binaries/bin
wget https://akreidieh.s3.amazonaws.com/sumo/flow-0.4.0/binaries-ubuntu1804.tar.xz
tar -xf binaries-ubuntu1804.tar.xz
rm binaries-ubuntu1804.tar.xz
chmod +x *
popd
echo 'export PATH="$HOME/sumo_binaries/bin:$PATH"' >> ~/.bashrc
echo 'export SUMO_HOME="$HOME/sumo_binaries/bin"' >> ~/.bashrc
echo "** Done **"

echo "To complete set up we need to close this terminal window"
echo "Click on the ENTER key to close this window"
read -s -n 1 key
if [[ $key = "" ]];
then
  exit
fi
