#!/bin/bash
# This bash script is to facilitate selecting which scenario to launch in SUMO
# Usage:
# ------
#
# >> ./launch_sumo scenario=[0 | 1 | 2 | 3]
#	0 = OSM Scenario
#	1 = 1-lane highway
#	2 = 2-lane highway
#	3 = 1-lane square scenario

IFS== read var1 var2 <<< $1

./waf --run "scratch/ns3-sumo-coupling-simple --scenario=$var2" 2>&1 | awk '{print > "rl_fyp/ns3_logs/speed_control/logs.log"}/RSU0 table/{print > "rl_fyp/ns3_logs/speed_control/rsu_0.log"}/MyGetReward/{print > "rl_fyp/ns3_logs/speed_control/rewards.log"}'
